spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness_activity_db
      database: fitness_activity_db
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#RabbitMQ
rabbitmq:
  exchange:
    name: finess.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking