spring:
#  application:
#    name: ai-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness_ai_db
      database: fitness_ai_db
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#RabbitMQ
rabbitmq:
  exchange:
    name: finess.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

gemni:
  api:
    url: ${GEMNI_API_URL}
    key: ${GEMNI_API_KEY}